version: '2'
services:
    agreen-mongodb:
        container_name: agreen-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/agreen/mongodb/:/data/db/
